name = "jubart"
uuid = "288234cd-5ce7-4dd2-8897-c903ad25b578"
authors = ["Bruna Wundervald", "Mateus Maia"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[targets]
test = ["Test"]
